
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class TIC_TAC_TOE extends javax.swing.JFrame {
    int turn=2;
    int bu[]={0,0,0,0,0,0,0,0,0};
    int p1won[]={0,0,0,0,0,0,0,0,0};
    int p2won[]={0,0,0,0,0,0,0,0,0};
    int p1won()
    {
        if(p1won[0]==1 && p1won[1]==1 && p1won[2]==1)
        {
            return 1; }
           if(p1won[3]==1 && p1won[4]==1 && p1won[5]==1)
        {
            return 1; }
              if(p1won[6]==1 && p1won[7]==1 && p1won[8]==1)
        {
            return 1; }
                 if(p1won[0]==1 && p1won[3]==1 && p1won[6]==1)
        {
            return 1; }
                    if(p1won[1]==1 && p1won[4]==1 && p1won[7]==1)
        {
            return 1; }
                       if(p1won[2]==1 && p1won[5]==1 && p1won[8]==1)
        {
            return 1; }
                          if(p1won[2]==1 && p1won[4]==1 && p1won[6]==1)
        {
            return 1; }
                             if(p1won[0]==1 && p1won[4]==1 && p1won[8]==1)
        {
            return 1; }
                             return 0;
    }
    
    
    int p2won()
    {
        if(p2won[0]==1 && p2won[1]==1 && p2won[2]==1)
        {
            return 1; }
           if(p2won[3]==1 && p2won[4]==1 && p2won[5]==1)
        {
            return 1; }
              if(p2won[6]==1 && p2won[7]==1 && p2won[8]==1)
        {
            return 1; }
                 if(p2won[0]==1 && p2won[3]==1 && p2won[6]==1)
        {
            return 1; }
                    if(p2won[1]==1 && p2won[4]==1 && p2won[7]==1)
        {
            return 1; }
                       if(p2won[2]==1 && p2won[5]==1 && p2won[8]==1)
        {
            return 1; }
                          if(p2won[2]==1 && p2won[4]==1 && p2won[6]==1)
        {
            return 1; }
                             if(p2won[0]==1 && p2won[4]==1 && p2won[8]==1)
        {
            return 1; }
                             return 0;
    }
 
    
    public TIC_TAC_TOE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pos = new javax.swing.JLabel();
        pxs = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 97, 84));

        b2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 97, 84));

        b3.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 97, 84));

        b4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 97, 84));

        b5.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 97, 84));

        b6.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 97, 84));

        b7.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 97, 84));

        b8.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 97, 84));

        b9.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 97, 84));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("Restart the score and Play Again");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 260, 51));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 0, 50, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Player X :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 88, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("SCORE BOARD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 175, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Player O :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 88, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 151, 230, -1));

        pos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pos.setText("0");
        getContentPane().add(pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 77, -1));

        pxs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pxs.setText("0");
        getContentPane().add(pxs, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 77, -1));

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("TIC TAC TOE GAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 11, 285, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jButton3.setText("Restart game without changing Score");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 320, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pexels-photo-1037998.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
if(bu[0]==0){        
        if(turn%2==0){
    turn++;
    b1.setText("X");
    b1.setForeground(Color.red);
    bu[0]=1;
    p1won[0]=1;
    int res1=p1won();
    int res2=p2won();
    if(res1==1){
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 "
                + "color=red>** Player X has Won this Round **",null,2);
    pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
    b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++) {
    bu[i]=0;         }
for(int i=0;i<9;i++) {
    p1won[i]=0;      }
for(int i=0;i<9;i++) {
    p2won[i]=0;      }
}
    else if(res2==1) {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 "
                + "color=blue>** Player O has Won this Round **",null,2);
    pos.setText(""+(Integer.parseInt(pos.getText())+1));
    b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++) {
    bu[i]=0;         }
for(int i=0;i<9;i++) {
    p1won[i]=0;      }
for(int i=0;i<9;i++) {
    p2won[i]=0;      }
}    
}
else {
    turn++;
    b1.setText("O");
    b1.setForeground(Color.blue);
    bu[0]=1;
    p2won[0]=1;
      int res1=p1won();
    int res2=p2won();
    if(res1==1) {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
   pos.setText(""+(Integer.parseInt(pos.getText())+1));
   b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
    
        } 
}        
else 
{
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10>! This Button is Already used !",null,0);
}
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
if(bu[1]==0)
{        
        if(turn%2==0)
{
    turn++;
    b2.setText("X");
    b2.setForeground(Color.red);
    bu[1]=1;
    p1won[1]=1;
    int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
    pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
    b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        pos.setText(""+(Integer.parseInt(pos.getText())+1));
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
}
else {
    turn++;
    b2.setText("O");
    b2.setForeground(Color.blue);
    bu[1]=1;
    p2won[1]=1;
      int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
    pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
    b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        pos.setText(""+(Integer.parseInt(pos.getText())+1));
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
    
        } 
}        
else 
{
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10>! This Button is Already used !",null,0);
}
            // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
  if(bu[2]==0)
{        
        if(turn%2==0)
{
    turn++;
    b3.setText("X");
    b3.setForeground(Color.red);
    bu[2]=1;
    p1won[2]=1;
    int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
}
else {
    turn++;
    b3.setText("O");
    b3.setForeground(Color.blue);
    bu[2]=1;
    p2won[2]=1;
      int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
    pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
    
        } 
}        
else 
{
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10>! This Button is Already used !",null,0);
}
        
      // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
       if(bu[3]==0)
{        
        if(turn%2==0)
{
    turn++;
    b4.setText("X");
    b4.setForeground(Color.red);
    bu[3]=1;
    p1won[3]=1;
    int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
    pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
}
else {
    turn++;
    b4.setText("O");
    b4.setForeground(Color.blue);
    bu[3]=1;
    p2won[3]=1;
      int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
    
        } 
}        
else 
{
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10>! This Button is Already used !",null,0);
}
        
 // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
    if(bu[4]==0)
{        
        if(turn%2==0)
{
    turn++;
    b5.setText("X");
    b5.setForeground(Color.red);
    bu[4]=1;
    p1won[4]=1;
    int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
    pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
}
else {
    turn++;
    b5.setText("O");
    b5.setForeground(Color.blue);
    bu[4]=1;
    p2won[4]=1;
      int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
    pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
    
        } 
}        
else 
{
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10>! This Button is Already used !",null,0);
}
        
    // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
     if(bu[5]==0)
{        
        if(turn%2==0)
{
    turn++;
    b6.setText("X");
    b6.setForeground(Color.red);
    bu[5]=1;
    p1won[5]=1;
    int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
    pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
}
else {
    turn++;
    b6.setText("O");
    b6.setForeground(Color.blue);
    bu[5]=1;
    p2won[5]=1;
      int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
  pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
    
        } 
}        
else 
{
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10>! This Button is Already used !",null,0);
}
        
   // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
    if(bu[6]==0)
{        
        if(turn%2==0)
{
    turn++;
    b7.setText("X");
    b7.setForeground(Color.red);
    bu[6]=1;
    p1won[6]=1;
    int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
}
else {
    turn++;
    b7.setText("O");
    b7.setForeground(Color.blue);
    bu[6]=1;
    p2won[6]=1;
      int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
    
        } 
}        
else 
{
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10>! This Button is Already used !",null,0);
}
        
    // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
     if(bu[7]==0)
{        
        if(turn%2==0)
{
    turn++;
    b8.setText("X");
    b8.setForeground(Color.red);
    bu[7]=1;
    p1won[7]=1;
    int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
}
else {
    turn++;
    b8.setText("O");
    b8.setForeground(Color.blue);
    bu[7]=1;
    p2won[7]=1;
      int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
     pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
    
        } 
}        
else 
{
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10>! This Button is Already used !",null,0);
}
        
   // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
      if(bu[8]==0)
{        
        if(turn%2==0)
{
    turn++;
    b9.setText("X");
    b9.setForeground(Color.red);
    bu[8]=1;
    p1won[8]=1;
    int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
     pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
    pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
}
else {
    turn++;
    b9.setText("O");
    b9.setForeground(Color.blue);
    bu[8]=1;
    p2won[8]=1;
      int res1=p1won();
    int res2=p2won();
    if(res1==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=red>** Player X has Won this Round **",null,2);
  pxs.setText(""+(Integer.parseInt(pxs.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=1;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    else if(res2==1)
    {
        JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10 color=blue>** Player O has Won this Round **",null,2);
    pos.setText(""+(Integer.parseInt(pos.getText())+1));
     b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

    }
    
    
        } 
}        
else 
{
    JOptionPane.showMessageDialog(this,"<html><font face=rockwell size=10>! This Button is Already used !",null,0);
}
        
  // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(Integer.parseInt(pxs.getText())==0 && Integer.parseInt(pos.getText())==0)
      JOptionPane.showMessageDialog(this,"<html><font face=Franklin Gothic size=10 color=red ><center>** Strart Playing ** </center>",null,2);

else if(Integer.parseInt(pxs.getText())>Integer.parseInt(pos.getText()))
      JOptionPane.showMessageDialog(this,"<html><font face=Franklin Gothic size=10 color=orange><center>Hurray!  Player X has Won The Game <br> Best Of Luck , Play Again</center>",null,2);
else 
    if(Integer.parseInt(pxs.getText())<Integer.parseInt(pos.getText()))
      JOptionPane.showMessageDialog(this,"<html><font face=Franklin Gothic size=10 color=orange><center>Hurray!  Player O has Won The Game <br> Best Of Luck , Play Again</center>",null,2);
    else 
       
      JOptionPane.showMessageDialog(this,"<html><font face=Franklin Gothic size=10 color=orange><center>Oh!  Game Tied  <br> Best Of Luck , Play Again</center>",null,2);
pxs.setText("0");
pos.setText("0");
        b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        b1.setText("");    
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");
b9.setText("");
turn=2;
for(int i=0;i<9;i++)
{
    bu[i]=0;
}
for(int i=0;i<9;i++)
{
    p1won[i]=0;
}for(int i=0;i<9;i++)
{
    p2won[i]=0;
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIC_TAC_TOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIC_TAC_TOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIC_TAC_TOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIC_TAC_TOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TIC_TAC_TOE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pos;
    private javax.swing.JLabel pxs;
    // End of variables declaration//GEN-END:variables
}
